import { SKILL_EQUIV_FRACTIONS, SKILL_ADD_LIKE_FRACTIONS, SKILL_SUB_LIKE_FRACTIONS, SKILL_SIMPLIFY_FRACTIONS } from './grade4-fractions';
import { SKILL_DECIMAL_NOTATION } from './grade4-decimals';
import type { Skill } from '../types';

export const ALL_SKILLS_LIST: Skill[] = [
    SKILL_EQUIV_FRACTIONS,
    SKILL_ADD_LIKE_FRACTIONS,
    SKILL_SUB_LIKE_FRACTIONS,
    SKILL_SIMPLIFY_FRACTIONS,
    SKILL_DECIMAL_NOTATION
];
