import {
  SKILL_EQUIV_FRACTIONS,
  SKILL_ADD_LIKE_FRACTIONS,
  SKILL_SUB_LIKE_FRACTIONS,
  SKILL_SIMPLIFY_FRACTIONS,
  SKILL_FRAC_MULT_WHOLE,
  SKILL_FRAC_COMPARE_UNLIKE,
  SKILL_ADD_TENTHS_HUNDREDTHS,
} from "./grade4-fractions";
import {
  SKILL_AREA_PERIMETER,
  SKILL_UNIT_CONVERSION,
  SKILL_GEO_LINES_ANGLES,
  SKILL_SYMMETRY,
  SKILL_ANGLES_MEASURE,
  SKILL_LINE_PLOTS,
  SKILL_SHAPE_CLASSIFICATION,
  SKILL_MONEY_WORD_PROBLEMS,
  SKILL_PROTRACTOR_MEASURE,
} from "./grade4-meas-geo";
import {
  SKILL_DECIMAL_NOTATION,
  SKILL_DECIMAL_COMPARE,
} from "./grade4-decimals";
import {
  SKILL_PLACE_VALUE,
  SKILL_COMPARE_MULTI_DIGIT,
  SKILL_ROUNDING,
  SKILL_ADD_SUB_MULTI,
  SKILL_MULT_1DIGIT,
  SKILL_MULT_2DIGIT,
  SKILL_DIV_REMAINDERS,
} from "./grade4-nbt";
import {
  SKILL_FACTORS_MULTIPLES,
  SKILL_PATTERNS,
  SKILL_MULT_COMPARE,
  SKILL_MULTI_STEP_WORD_PROBLEMS,
} from "./grade4-oa";
import {
  SKILL_5_NBT_POWERS_10,
  SKILL_5_NBT_DECIMAL_FORMS,
  SKILL_5_NBT_COMPARE_DECIMALS,
  SKILL_5_NBT_ROUND_DECIMALS,
  SKILL_5_NBT_ADD_SUB_DECIMALS,
  SKILL_5_NBT_MULT_WHOLE,
  SKILL_5_NBT_MULT_DECIMALS,
  SKILL_5_NBT_DIV_WHOLE,
  SKILL_5_NBT_DIV_DECIMALS,
} from "./grade5-nbt";
import type { Skill } from "../types";

export const ALL_SKILLS_LIST: Skill[] = [
  // Grade 4
  SKILL_EQUIV_FRACTIONS,
  SKILL_ADD_LIKE_FRACTIONS,
  SKILL_SUB_LIKE_FRACTIONS,
  SKILL_SIMPLIFY_FRACTIONS,
  SKILL_FRAC_MULT_WHOLE,
  SKILL_FRAC_COMPARE_UNLIKE,
  SKILL_ADD_TENTHS_HUNDREDTHS,
  SKILL_DECIMAL_NOTATION,
  SKILL_DECIMAL_COMPARE,
  SKILL_PLACE_VALUE,
  SKILL_COMPARE_MULTI_DIGIT,
  SKILL_ROUNDING,
  SKILL_ADD_SUB_MULTI,
  SKILL_MULT_1DIGIT,
  SKILL_MULT_2DIGIT,
  SKILL_DIV_REMAINDERS,
  SKILL_FACTORS_MULTIPLES,
  SKILL_PATTERNS,
  SKILL_MULT_COMPARE,
  SKILL_MULTI_STEP_WORD_PROBLEMS,
  SKILL_AREA_PERIMETER,
  SKILL_UNIT_CONVERSION,
  SKILL_GEO_LINES_ANGLES,
  SKILL_SYMMETRY,
  SKILL_ANGLES_MEASURE,
  SKILL_LINE_PLOTS,
  SKILL_SHAPE_CLASSIFICATION,
  SKILL_MONEY_WORD_PROBLEMS,
  SKILL_PROTRACTOR_MEASURE,

  // Grade 5 (NBT Domain Complete)
  SKILL_5_NBT_POWERS_10,
  SKILL_5_NBT_DECIMAL_FORMS,
  SKILL_5_NBT_COMPARE_DECIMALS,
  SKILL_5_NBT_ROUND_DECIMALS,
  SKILL_5_NBT_ADD_SUB_DECIMALS,
  SKILL_5_NBT_MULT_WHOLE,
  SKILL_5_NBT_MULT_DECIMALS,
  SKILL_5_NBT_DIV_WHOLE,
  SKILL_5_NBT_DIV_DECIMALS,
];
