import {
  SKILL_EQUIV_FRACTIONS,
  SKILL_ADD_LIKE_FRACTIONS,
  SKILL_SUB_LIKE_FRACTIONS,
  SKILL_SIMPLIFY_FRACTIONS,
  SKILL_FRAC_MULT_WHOLE,
  SKILL_FRAC_COMPARE_UNLIKE,
  SKILL_ADD_TENTHS_HUNDREDTHS,
  SKILL_FRAC_DECOMPOSE,
  SKILL_ADD_SUB_MIXED,
} from "./grade4-fractions";
import {
  SKILL_AREA_PERIMETER,
  SKILL_UNIT_CONVERSION,
  SKILL_GEO_LINES_ANGLES,
  SKILL_SYMMETRY,
  SKILL_ANGLES_MEASURE,
  SKILL_LINE_PLOTS,
  SKILL_SHAPE_CLASSIFICATION,
  SKILL_MONEY_WORD_PROBLEMS,
  SKILL_PROTRACTOR_MEASURE,
} from "./grade4-meas-geo";
import {
  SKILL_DECIMAL_NOTATION,
  SKILL_DECIMAL_COMPARE,
} from "./grade4-decimals";
import {
  SKILL_PLACE_VALUE,
  SKILL_COMPARE_MULTI_DIGIT,
  SKILL_ROUNDING,
  SKILL_ADD_SUB_MULTI,
  SKILL_MULT_1DIGIT,
  SKILL_MULT_2DIGIT,
  SKILL_DIV_REMAINDERS,
} from "./grade4-nbt";
import {
  SKILL_FACTORS_MULTIPLES,
  SKILL_PATTERNS,
  SKILL_MULT_COMPARE,
  SKILL_MULTI_STEP_WORD_PROBLEMS,
} from "./grade4-oa";
import {
  SKILL_5_NBT_POWERS_10,
  SKILL_5_NBT_DECIMAL_FORMS,
  SKILL_5_NBT_COMPARE_DECIMALS,
  SKILL_5_NBT_ROUND_DECIMALS,
  SKILL_5_NBT_ADD_SUB_DECIMALS,
  SKILL_5_NBT_MULT_WHOLE,
  SKILL_5_NBT_MULT_DECIMALS,
  SKILL_5_NBT_DIV_WHOLE,
  SKILL_5_NBT_DIV_DECIMALS,
} from "./grade5-nbt";
import {
  SKILL_5_NF_ADD_SUB_UNLIKE,
  SKILL_5_NF_FRAC_DIV,
  SKILL_5_NF_SCALING,
  SKILL_5_NF_MULT_FRAC,
  SKILL_5_NF_DIV_FRAC,
  SKILL_5_NF_WORD_PROBLEMS,
} from "./grade5-fractions";
import {
  SKILL_5_GM_VOLUME_CUBES,
  SKILL_5_GM_VOLUME_FORMULA,
  SKILL_5_GM_COORD_PLANE,
  SKILL_5_GM_CLASS_FIGURES,
  SKILL_5_GM_UNIT_CONV,
  SKILL_5_MD_LINE_PLOTS,
} from "./grade5-meas-geo";
import { SKILL_5_OA_ORDER_OPS, SKILL_5_OA_PATTERNS } from "./grade5-oa";
import { SKILL_6_RP_RATIOS, SKILL_6_RP_UNIT_RATE } from "./grade6-rp";
import {
  SKILL_6_NS_DIV_FRACTIONS,
  SKILL_6_NS_MULTI_DIGIT_DIV,
} from "./grade6-ns";
import { SKILL_6_EE_EXPONENTS, SKILL_6_EE_ONE_STEP_EQ } from "./grade6-ee";
import { SKILL_6_G_AREA } from "./grade6-geometry";
import { SKILL_6_SP_MEAN } from "./grade6-stats";

import type { Skill } from "../types";

export const ALL_SKILLS_LIST: Skill[] = [
  // Grade 4
  SKILL_EQUIV_FRACTIONS,
  SKILL_ADD_LIKE_FRACTIONS,
  SKILL_SUB_LIKE_FRACTIONS,
  SKILL_SIMPLIFY_FRACTIONS,
  SKILL_FRAC_MULT_WHOLE,
  SKILL_FRAC_COMPARE_UNLIKE,
  SKILL_ADD_TENTHS_HUNDREDTHS,
  SKILL_FRAC_DECOMPOSE,
  SKILL_ADD_SUB_MIXED,
  SKILL_DECIMAL_NOTATION,
  SKILL_DECIMAL_COMPARE,
  SKILL_PLACE_VALUE,
  SKILL_COMPARE_MULTI_DIGIT,
  SKILL_ROUNDING,
  SKILL_ADD_SUB_MULTI,
  SKILL_MULT_1DIGIT,
  SKILL_MULT_2DIGIT,
  SKILL_DIV_REMAINDERS,
  SKILL_FACTORS_MULTIPLES,
  SKILL_PATTERNS,
  SKILL_MULT_COMPARE,
  SKILL_MULTI_STEP_WORD_PROBLEMS,
  SKILL_AREA_PERIMETER,
  SKILL_UNIT_CONVERSION,
  SKILL_GEO_LINES_ANGLES,
  SKILL_SYMMETRY,
  SKILL_ANGLES_MEASURE,
  SKILL_LINE_PLOTS,
  SKILL_SHAPE_CLASSIFICATION,
  SKILL_MONEY_WORD_PROBLEMS,
  SKILL_PROTRACTOR_MEASURE,

  // Grade 5 NBT
  SKILL_5_NBT_POWERS_10,
  SKILL_5_NBT_DECIMAL_FORMS,
  SKILL_5_NBT_COMPARE_DECIMALS,
  SKILL_5_NBT_ROUND_DECIMALS,
  SKILL_5_NBT_ADD_SUB_DECIMALS,
  SKILL_5_NBT_MULT_WHOLE,
  SKILL_5_NBT_MULT_DECIMALS,
  SKILL_5_NBT_DIV_WHOLE,
  SKILL_5_NBT_DIV_DECIMALS,

  // Grade 5 NF
  SKILL_5_NF_ADD_SUB_UNLIKE,
  SKILL_5_NF_FRAC_DIV,
  SKILL_5_NF_SCALING,
  SKILL_5_NF_MULT_FRAC,
  SKILL_5_NF_DIV_FRAC,
  SKILL_5_NF_WORD_PROBLEMS,

  // Grade 5 GM
  SKILL_5_GM_VOLUME_CUBES,
  SKILL_5_GM_VOLUME_FORMULA,
  SKILL_5_GM_COORD_PLANE,
  SKILL_5_GM_CLASS_FIGURES,
  SKILL_5_GM_UNIT_CONV,
  SKILL_5_MD_LINE_PLOTS,

  // Grade 5 OA
  SKILL_5_OA_ORDER_OPS,
  SKILL_5_OA_PATTERNS,

  // Grade 6 RP
  SKILL_6_RP_RATIOS,
  SKILL_6_RP_UNIT_RATE,

  // Grade 6 NS
  SKILL_6_NS_DIV_FRACTIONS,
  SKILL_6_NS_MULTI_DIGIT_DIV,

  // Grade 6 EE
  SKILL_6_EE_EXPONENTS,
  SKILL_6_EE_ONE_STEP_EQ,

  // Grade 6 Geometry
  SKILL_6_G_AREA,

  // Grade 6 Stats
  SKILL_6_SP_MEAN,
];
